const supertest = require("supertest");
const { app } = require("../src/server");

const api = supertest(app);

const fakeData = [
  {
    first_name: "Crystal",
    last_name: "Galtone",
    email: "cgaltone0@cnet.com",
    username: "cgaltone0",
    gender: "Female",
    age: 32,
  },
  {
    first_name: "Jule",
    last_name: "Huttley",
    email: "jhuttley1@liveinternet.ru",
    username: "jhuttley1",
    gender: "Male",
    age: 50,
  },
  {
    first_name: "Tyler",
    last_name: "Kenworth",
    email: "tkenworth2@pbs.org",
    username: "tkenworth2",
    gender: "Male",
    age: 22,
  },
  {
    first_name: "Rosemonde",
    last_name: "Channing",
    email: "rchanning3@cbslocal.com",
    username: "rchanning3",
    gender: "Female",
    age: 26,
  },
  {
    first_name: "Logan",
    last_name: "Bakster",
    email: "lbakster4@blog.com",
    username: "lbakster4",
    gender: "Male",
    age: 47,
  },
  {
    first_name: "Zaneta",
    last_name: "MacCleay",
    email: "zmaccleay5@ox.ac.uk",
    username: "zmaccleay5",
    gender: "Female",
    age: 21,
  },
  {
    first_name: "Robyn",
    last_name: "Yakunchikov",
    email: "ryakunchikov6@google.es",
    username: "ryakunchikov6",
    gender: "Female",
    age: 33,
  },
  {
    first_name: "Aaron",
    last_name: "Mateu",
    email: "amateu7@squarespace.com",
    username: "amateu7",
    gender: "Male",
    age: 50,
  },
  {
    first_name: "Jon",
    last_name: "Brotherwood",
    email: "jbrotherwood8@barnesandnoble.com",
    username: "jbrotherwood8",
    gender: "Male",
    age: 35,
  },
  {
    first_name: "Alasteir",
    last_name: "Habin",
    email: "ahabin9@mapy.cz",
    username: "ahabin9",
    gender: "Male",
    age: 23,
  },
  {
    first_name: "Duffie",
    last_name: "Thacke",
    email: "dthackea@cmu.edu",
    username: "dthackea",
    gender: "Male",
    age: 18,
  },
  {
    first_name: "Glenn",
    last_name: "Coffey",
    email: "gcoffeyb@usatoday.com",
    username: "gcoffeyb",
    gender: "Male",
    age: 42,
  },
  {
    first_name: "Fidelio",
    last_name: "Lieb",
    email: "fliebc@indiatimes.com",
    username: "fliebc",
    gender: "Male",
    age: 44,
  },
  {
    first_name: "Saidee",
    last_name: "Demead",
    email: "sdemeadd@ucoz.com",
    username: "sdemeadd",
    gender: "Female",
    age: 23,
  },
  {
    first_name: "Homerus",
    last_name: "Melpuss",
    email: "hmelpusse@wikispaces.com",
    username: "hmelpusse",
    gender: "Male",
    age: 19,
  },
  {
    first_name: "Marshall",
    last_name: "Persian",
    email: "mpersianf@goo.gl",
    username: "mpersianf",
    gender: "Male",
    age: 30,
  },
  {
    first_name: "Clevey",
    last_name: "Sola",
    email: "csolag@boston.com",
    username: "csolag",
    gender: "Male",
    age: 32,
  },
  {
    first_name: "Missy",
    last_name: "Wortman",
    email: "mwortmanh@scientificamerican.com",
    username: "mwortmanh",
    gender: "Female",
    age: 33,
  },
  {
    first_name: "Glenn",
    last_name: "Hutchason",
    email: "ghutchasoni@bravesites.com",
    username: "ghutchasoni",
    gender: "Male",
    age: 41,
  },
  {
    first_name: "Cacilie",
    last_name: "Ecclesall",
    email: "cecclesallj@altervista.org",
    username: "cecclesallj",
    gender: "Female",
    age: 33,
  },
  {
    first_name: "Clary",
    last_name: "Downton",
    email: "cdowntonk@jiathis.com",
    username: "cdowntonk",
    gender: "Female",
    age: 39,
  },
  {
    first_name: "Gibbie",
    last_name: "Larive",
    email: "glarivel@ustream.tv",
    username: "glarivel",
    gender: "Male",
    age: 20,
  },
  {
    first_name: "Ned",
    last_name: "Axelby",
    email: "naxelbym@myspace.com",
    username: "naxelbym",
    gender: "Male",
    age: 20,
  },
  {
    first_name: "Eberto",
    last_name: "Braley",
    email: "ebraleyn@tamu.edu",
    username: "ebraleyn",
    gender: "Male",
    age: 29,
  },
  {
    first_name: "Florenza",
    last_name: "Dance",
    email: "fdanceo@cyberchimps.com",
    username: "fdanceo",
    gender: "Female",
    age: 18,
  },
];

const getAllUsers = async () => {
  return await api.get("/user");
};

module.exports = { fakeData, getAllUsers };
